  CREATE TABLE baseball_platinum.play (
      "playPk"                      BIGSERIAL PRIMARY KEY,
      "gamePk"                      INT NOT NULL,
      "atBatId"                     INT NOT NULL,
      "pitcherId"                   INT NOT NULL,
      "batterId"                    INT NOT NULL,
      "postOnFirstId"               INT,
      "postOnSecondId"              INT,
      "postOnThirdId"               INT,
      "batterPlayIndex"             INT NOT NULL,
      "playId"                      TEXT,
      "batterPitchNumber"           INT,
      "captivatingIndex"            INT,
      "inning"                      INT,
      "halfInning"                  TEXT,
      "resultType"                  TEXT,
      "resultEvent"                 TEXT,
      "resultEventType"             TEXT,
      "resultEventDescription"      TEXT,
      "playCallCode"                TEXT,
      "playCallDescription"         TEXT,
      "playCode"                    TEXT,
      "playDescription"             TEXT,
      "pitchTypeCode"               TEXT,
      "pitchTypeDescription"        TEXT,
      "pitcherSplits"               TEXT,
      "pitcherHotColdZones"         JSON,
      "pitchData"                   JSON,
      "batterSplits"                TEXT,
      "batterHotColdZones"          JSON,
      "hitData"                     JSON,
      "runnerSplits"                TEXT,
      "runnerData"                  JSON,
      "atBatStartTime"              timestamptz,
      "atBatEndTime"                timestamptz,
      "playStartTime"               timestamptz,
      "playEndTime"                 timestamptz,
      "isTopInning"                 BOOLEAN,
      "isPitch"                     BOOLEAN,
      "isStrike"                    BOOLEAN,
      "isBall"                      BOOLEAN,
      "isAtBatComplete"             BOOLEAN,
      "isInPlay"                    BOOLEAN,
      "isScoringPlay"               BOOLEAN,
      "isBatterOut"                 BOOLEAN,
      "hasOutRecorded"              BOOLEAN,
      "atBatHasReview"              BOOLEAN,
      "hasReview"                   BOOLEAN,
      "countBalls"                  INT,
      "countStrikes"                INT,
      "countOuts"                   INT,
      "awayScore"                   INT,
      "homeScore"                   INT,
      "RBIs"                        INT,
      "_createdAt"                  TIMESTAMP,
      "_createdBy"                  TEXT
  );

SELECT "playCode", "playDescription", "playCallCode", "playCallDescription", "countStrikes"
FROM baseball_platinum.play
where "countStrikes" = 3 or
      ("isInPlay" and "isBatterOut")