CREATE TABLE baseball_platinum.player
(
    "playerHistoryId"               SERIAL PRIMARY KEY, -- keep track of team changes (if any)
    "playerId"                      INT NOT NULL,
    "teamId"                        INT,
    "fullName"                      VARCHAR,
    "firstName"                     VARCHAR,
    "middleName"                    VARCHAR,
    "lastName"                      VARCHAR,
    "birthCity"                     VARCHAR,
    "birthStateProvince"            VARCHAR,
    "birthCountry"                  VARCHAR,
    "useName"                       VARCHAR,
    "useLastName"                   VARCHAR,
    "boxScoreName"                  VARCHAR,
    "nickname"                      VARCHAR,
    "nameTitle"                     VARCHAR,
    "nameSuffix"                    VARCHAR,
    "nameMatrilineal"               VARCHAR,
    "namePronunciation"             VARCHAR,
    "birthDate"                     DATE,
    age                             INT,
    gender                          VARCHAR,
    height                          VARCHAR,
    weight                          INT,
    "draftYear"                     INT,
    "mlbDebutDate"                  DATE,
    "primaryNumber"                  INT,
    "primaryPositionCode"           VARCHAR,
    "primaryPositionName"           VARCHAR,
    "primaryPositionType"           VARCHAR,
    "primaryPositionAbbreviation"   VARCHAR,
    "batSideCode"                   VARCHAR,
    "batSideDescription"            VARCHAR,
    "pitchHandCode"                 VARCHAR,
    "pitchHandDescription"          VARCHAR,
    "strikeZoneTop"                 NUMERIC(3,2),
    "strikeZoneBottom"              NUMERIC(3,2),
    "apiLink"                       VARCHAR,
    "isPlayer"                      BOOLEAN,
    "isVerified"                    BOOLEAN,
    "isActive"                      BOOLEAN,
    "_createdAt"                    TIMESTAMP,
    "updatedAt"                     timestamp
);