CREATE TABLE baseball_platinum.runner
(
    "runPk"                 SERIAL PRIMARY KEY,
    "gamePk"                INT,
    "runnerId"              INT,
    "pitcherId"             INT,
    "responsiblePitcherId"  INT,
    "postOnFirstId"         INT,
    "postOnSecondId"        INT,
    "postOnThirdId"         INT,
    "atBatId"               INT,
    "batterPlayId"          INT,
    "eventType"             TEXT,
    "originBase"            TEXT,
    "startBase"             TEXT,
    "endBase"               TEXT,
    "outBase"               TEXT,
    "outNumber"             INT,
    "isStolenBase"          BOOLEAN,
    "isCaughtStealing"      BOOLEAN,
    "isOut"                 BOOLEAN,
    "isRBI"                 BOOLEAN,
    "isEarnedRun"           BOOLEAN,
    "isUnearnedRun"         BOOLEAN,
    "_createdAt"            TIMESTAMP,
    "_updatedAt"            TIMESTAMP
    )