CREATE TABLE IF NOT EXISTS baseball_platinum.team
(
    team_id                     int PRIMARY KEY,
    venue_id                    int,
    spring_venue_id             int,
    division_id                 int,
    league_id                   int,
    spring_league_id            int,
    sport_id                    int,
    franchise_name              varchar,
    team_name                   varchar,
    short_name                  varchar,
    abbreviation                varchar,
    club_name                   varchar,
    venue_name                  varchar,
    location_name               varchar,
    division_name               varchar,
    league_name                 varchar,
    spring_league_name          varchar,
    spring_league_abbreviation  varchar,
    sport_name                  varchar,
    season                      int,
    first_year_of_play          int,
    all_star_status             varchar,
    is_active                   bool,
    date_created                timestamp,
    date_updated                timestamp,
    created_by                  varchar,
    updated_by                  varchar
);