select * from baseball_models.player;


MERGE INTO baseball_models.player  target
USING ( select distinct * from baseball_platinum.players) source
    ON source.player_id = target."playerId"

WHEN MATCHED THEN
    UPDATE SET
            "teamId"        = source.team_id,
            "age"           = source.current_age,
            number          = source.primary_number,
            position        = source.primary_position_abbreviation,
            "batSide"       = source.bat_side_code,
            "mlbDebutDate"  = source.mlb_debut_date
WHEN NOT MATCHED THEN
INSERT ("playerId",
        "teamId",
        "fullName",
        "firstName",
        "middleName",
        "lastName",
        "birthCity",
        "birthStateProvince",
        "birthCountry",
        "useName",
        "useLastName",
        "boxScoreName",
        "nickName",
        "nameTitle",
        "nameSuffix",
        "nameMatrilineal",
        "nameFirstLast",
        "nameSlug",
        "firstLastName",
        "lastFirstName",
        "lastInitName",
        "initLastName",
        "fullFMLName",
        "fullFMName",
        pronunciation,
        "birthDate",
        "currentAge",
        "gender",
        "height",
        "weight",
        "draftYear",
        "mlbDebutDate",
        "primaryNumber",
        "primaryPositionCode",
        "primaryPositionName",
        "primaryPositionType",
        "primaryPositionAbbreviation",
        "batSideCode",
        "batSideDescription",
        "pitchHandCode",
        "pitchHandDescription",
        "isPlayer",
        "isVerified",
        "isActive",
        "strikeZoneTop",
        "strikeZoneBottom",
        "apiLink",
        "createdAt",
        "createdBy")
VALUES (player_id,
        team_id,
        full_name,
        first_name,
        middle_name,
        last_name,
        birth_city,
        birth_state_province,
        birth_country,
        use_name,
        use_last_name,
        box_score_name,
        nickname,
        name_title,
        name_suffix,
        name_matrilineal,
        name_first_last,
        name_slug,
        first_last_name,
        last_first_name,
        last_init_name,
        init_last_name,
        full_fml_name,
        full_lfm_name,
        last_name_pronunciation,
        birth_date,
        current_age,
        gender,
        height,
        weight,
        draft_year,
        mlb_debut_date,
        primary_number,
        primary_position_code,
        primary_position_name,
        primary_position_type,
        primary_position_abbreviation,
        bat_side_code,
        bat_side_description,
        pitch_hand_code,
        pitch_hand_description,
        is_player,
        is_verified, is_active,
        strike_zone_top,
        strike_zone_bottom,
        api_link,
        date_created,
        created_by);
