MERGE INTO baseball_platinum.player AS target
USING baseball_aluminum.player AS source
    ON target."playerId" = source."playerId"

WHEN MATCHED THEN UPDATE
    SET
        "fullName"              = source."fullName",
        "teamId"                = source."teamId",
        age                     = source."currentAge",
        "primaryNumber"         = source."primaryNumber",
        "primaryPositionName"   = source."primaryPosition",
        "batSideCode"           = source."batSide",
        "updatedAt"             = source."_createdAt"
WHEN NOT MATCHED THEN INSERT
    ("playerId",
     "teamId",
     "fullName",
     "firstName",
     "middleName",
     "lastName",
     "birthCity",
     "birthStateProvince",
     "birthCountry",
     "useName",
     "useLastName",
     "boxScoreName",
     nickname,
     "nameTitle",
     "nameSuffix",
     "nameMatrilineal",
     "namePronunciation",
     "birthDate",
     age,
     gender,
     height,
     weight,
     "draftYear",
     "mlbDebutDate",
     "primaryNumber",
     "primaryPositionCode",
     "primaryPositionName",
     "primaryPositionType",
     "primaryPositionAbbreviation",
     "batSideCode",
     "batSideDescription",
     "pitchHandCode",
     "pitchHandDescription",
     "strikeZoneTop",
     "strikeZoneBottom",
     "apiLink",
     "isPlayer",
     "isVerified",
     "isActive",
     "_createdAt",
     "updatedAt")
    VALUES ("playerId",
            "teamId",
            "fullName",
            "firstName",
            "middleName",
            "lastName",
            "birthCity",
            "birthStateProvince",
            "birthCountry",
            "useName",
            "useLastName",
            "boxScoreName",
            "nickName",
            "nameTitle",
            "nameSuffix",
            "nameMatrilineal",
            "pronunciation",
            "birthDate",
            "currentAge",
            gender,
            height,
            weight,
            "draftYear",
            "mlbDebutDate",
            "primaryNumber",
            "primaryPosition"->>'code',
            "primaryPosition"->>'name',
            "primaryPosition"->>'type',
            "primaryPosition"->>'abbreviation',
            "batSide"->>'code',
            "batSide"->>'description',
            "pitchHand"->>'code',
            "pitchHand"->>'description',
            "strikeZoneTop",
            "strikeZoneBottom",
            "link",
            "isPlayer",
            "isVerified",
            "active",
            "_createdAt",
            current_timestamp
           )
;
SELECT *
FROM baseball_platinum.player;

SELECT "pitcherId", "gameId", "teamId", "pitchCount", "inningsPitched", "hits", "runs", "walks", "homeruns", "strikeouts" FROM "baseball_models"."pitcherAppearance" AS "pitcherAppearance" WHERE "pitcherAppearance"."pitcherId" = '690953';
