--DROP SCHEMA IF EXISTS baseball_aluminum;

CREATE SCHEMA IF NOT EXISTS baseball_aluminum;

DROP TABLE IF EXISTS baseball_aluminum.teams;

CREATE TABLE IF NOT EXISTS baseball_aluminum.teams
(
    teams_id                    int,
    venue_id                    int,
    spring_venue_id             int,
    division_id                 int,
    league_id                   int,
    spring_league_id            int,
    sport_id                    int,
    franchise_name              varchar,
    team_name                   varchar,
    short_name                  varchar,
    abbreviation                varchar,
    club_name                   varchar,
    venue_name                  varchar,
    location_name               varchar,
    division_name               varchar,
    league_name                 varchar,
    spring_league_name          varchar,
    spring_league_abbreviation  varchar,
    sport_name                  varchar,
    season                      int,
    first_year_of_play          int,
    all_star_status             varchar,
    is_active                   bool,
    date_loaded                timestamp,
    created_by                  varchar
);

DROP TABLE IF EXISTS baseball_aluminum.players;

CREATE TABLE IF NOT EXISTS baseball_aluminum.players
(
    player_id                       INT,
    team_id                         INT,
    full_name                       VARCHAR,
    first_Name                      VARCHAR,
    middle_name                     VARCHAR,
    last_name                       VARCHAR,
    birth_city                      VARCHAR,
    birth_state_province            VARCHAR,
    birth_country                   VARCHAR,
    use_name                        VARCHAR,
    use_last_name                   VARCHAR,
    box_score_name                  VARCHAR,
    nickname                        VARCHAR,
    name_title                      VARCHAR,
    name_suffix                     VARCHAR,
    name_matrilineal                VARCHAR,
    name_first_last                 VARCHAR,
    name_slug                       VARCHAR,
    first_last_name                 VARCHAR,
    last_first_name                 VARCHAR,
    last_init_name                  VARCHAR,
    init_last_name                  VARCHAR,
    full_fml_name                   VARCHAR,
    full_lfm_name                   VARCHAR,
    last_name_pronunciation         VARCHAR,
    birth_date                      DATE,
    current_age                     INT,
    gender                          VARCHAR,
    height                          VARCHAR,
    weight                          INT,
    draft_year                      INT,
    mlb_debut_date                  DATE,
    primary_number                  INT,
    primary_position_code           VARCHAR,
    primary_position_name           VARCHAR,
    primary_position_type           VARCHAR,
    primary_position_abbreviation   VARCHAR,
    bat_side_code                   VARCHAR,
    bat_side_description            VARCHAR,
    pitch_hand_code                 VARCHAR,
    pitch_hand_description          VARCHAR,
    is_player                       BOOLEAN,
    is_verified                     BOOLEAN,
    is_active                       BOOLEAN,
    strike_zone_top                 NUMERIC(3,2),
    strike_zone_bottom              NUMERIC(3,2),
    api_link                        VARCHAR,
    date_loaded                    TIMESTAMP,
    loaded_by                       VARCHAR
);

DROP TABLE IF EXISTS baseball_aluminum.schedule;

CREATE TABLE IF NOT EXISTS baseball_aluminum.schedule
(
    game_id             int,
    game_type           varchar,
    season              int,
    game_date           timestamp,
    official_date        date,
    status_code         varchar,
    detailed_state      varchar,
    away_team_id        int,
    away_team_is_winner bool,
    home_team_id        int,
    home_team_is_winner bool,
    venue_id            int,
    game_number         int,
    double_header       varchar,
    gameday_type        varchar,
    day_night           varchar,
    game_in_series      int,
    series_game_number  int,
    date_loaded         timestamp,
    created_by          varchar
);

DROP TABLE IF EXISTS baseball_aluminum.plays;
CREATE TABLE IF NOT EXISTS baseball_aluminum.plays
(
    about_game_id                           INT,
    about_at_bat_index                      INT,
    about_half_inning                       VARCHAR,
    about_is_top_inning                     BOOL,
    about_inning                                  INT,
    about_start_time                              TIMESTAMP,
    about_end_time                                TIMESTAMP,
    about_is_complete                             BOOL,
    about_is_scoring_play                         BOOL,
    about_has_review                        BOOL,
    about_has_out                        BOOL,
    about_captivating_index                 INT,
    matchup_batter_id                       INT,
    matchup_batter_full_name                VARCHAR,
    matchup_batter_link                     VARCHAR,
    matchup_bat_side_code                   VARCHAR,
    matchup_bat_side_description            VARCHAR,
    matchup_pitcher_id                      INT,
    matchup_pitcher_full_name               VARCHAR,
    matchup_pitcher_link                    VARCHAR,
    matchup_pitch_hand_code                 VARCHAR,
    matchup_pitch_hand_description          VARCHAR,
    matchup_post_on_first_id                        VARCHAR,
    matchup_post_on_first_full_name                 VARCHAR,
    matchup_post_on_first_link                      VARCHAR,
    matchup_post_on_second_id                       VARCHAR,
    matchup_post_on_second_full_name                VARCHAR,
    matchup_post_on_second_link                     VARCHAR,
    matchup_post_on_third_id                        VARCHAR,
    matchup_post_on_third_full_name                 VARCHAR,
    matchup_post_on_third_link                      VARCHAR,
    matchup_batter_hot_cold_zones                   JSON,
    matchup_pitcher_hot_cold_zones                  JSON,
    matchup_splits_batter                           VARCHAR,
    matchup_splits_pitcher                          VARCHAR,
    matchup_splits_men_on_base                      VARCHAR,
    result_type                             VARCHAR,
    result_event                            VARCHAR,
    result_event_type                       VARCHAR,
    result_event_description                VARCHAR,
    result_rbi                              INT,
    result_away_score                       INT,
    result_home_score                       INT,
    result_is_out                           BOOL,
    runners                                 JSON,
    play_outcome_details_call_code          VARCHAR,
    play_outcome_details_call_description   VARCHAR,
    play_outcome_description                VARCHAR,
    play_outcome_code                       VARCHAR,
    play_outcome_ball_color                 VARCHAR,
    play_outcome_trail_color                VARCHAR,
    play_outcome_is_in_play                 BOOL,
    play_outcome_is_strike                  BOOL,
    play_outcome_is_ball                    BOOL,
    play_outcome_type_code                  VARCHAR,
    play_outcome_type_description           VARCHAR,
    play_outcome_is_out                                     BOOL,
    play_outcome_has_review                                 BOOL,
    play_outcome_count_balls                             INT,
    play_outcome_count_strikes                           INT,
    play_outcome_count_outs                              INT,
    play_outcome_pitch_data_start_speed                  NUMERIC,
    play_outcome_pitch_data_end_speed                    NUMERIC,
    play_outcome_pitch_data_strike_zone_top              NUMERIC,
    play_outcome_pitch_data_strike_zone_bottom           NUMERIC,
    play_outcome_pitch_data_coordinates_ay               NUMERIC,
    play_outcome_pitch_data_coordinates_az               NUMERIC,
    play_outcome_pitch_data_coordinates_pfxx             NUMERIC,
    play_outcome_pitch_data_coordinates_pfxz             NUMERIC,
    play_outcome_pitch_data_coordinates_px               NUMERIC,
    play_outcome_pitch_data_coordinates_pz               NUMERIC,
    play_outcome_pitch_data_coordinates_vx0                      NUMERIC,
    play_outcome_pitch_data_coordinates_vy0                      NUMERIC,
    play_outcome_pitch_data_coordinates_vz0                      NUMERIC,
    play_outcome_pitch_data_coordinates_x                        NUMERIC,
    play_outcome_pitch_data_coordinates_y                        NUMERIC,
    play_outcome_pitch_data_coordinates_x0                       NUMERIC,
    play_outcome_pitch_data_coordinates_y0                       NUMERIC,
    play_outcome_pitch_data_coordinates_z0                       NUMERIC,
    play_outcome_pitch_data_coordinates_ax                       NUMERIC,
    play_outcome_pitch_data_breaks_break_angle                   NUMERIC,
    play_outcome_pitch_data_breaks_break_length                  NUMERIC,
    play_outcome_pitch_data_breaks_break_y                       NUMERIC,
    play_outcome_pitch_data_breaks_break_vertical                NUMERIC,
    play_outcome_pitch_data_breaks_break_vertical_induced        NUMERIC,
    play_outcome_pitch_data_breaks_break_horizontal              NUMERIC,
    play_outcome_pitch_data_breaks_spin_rate                     INTEGER,
    play_outcome_pitch_data_breaks_spin_direction                INTEGER,
    play_outcome_pitch_data_zone                                 Integer,
    play_outcome_pitch_data_type_confidence                      Numeric,
    play_outcome_pitch_data_plate_time                           NUMERIC,
    play_outcome_pitch_data_extension                            NUMERIC,
    play_outcome_hit_data_launch_speed                           NUMERIC,
    play_outcome_hit_data_launch_angle                           NUMERIC,
    play_outcome_hit_data_total_distance                         NUMERIC,
    play_outcome_hit_data_trajectory                             VARCHAR,
    play_outcome_hit_data_hardness                               VARCHAR,
    play_outcome_hit_data_location                               VARCHAR,
    play_outcome_hit_data_coordinates_coordx                     NUMERIC,
    play_outcome_hit_data_coordinates_coordy                     NUMERIC,
    play_outcome_index                                           INTEGER,
    play_outcome_play_id                                         VARCHAR,
    play_outcome_pitch_number                                    INTEGER,
    play_outcome_start_time                                      timestamptz,
    play_outcome_end_time                                        TIMESTAMPTZ,
    play_outcome_is_pitch                                        BOOL,
    play_outcome_type                                            VARCHAR,
    date_loaded                                                  TIMESTAMP,
    loaded_by                                                    VARCHAR
);


select * from baseball_raw.players;