CREATE TABLE baseball_aluminum.team
(
    "teamId" INT PRIMARY KEY,
    "springLeagueId" INT,
    "venueId" INT,
    "springVenueId" INT,
    "leagueId" INT,
    "divisionId" INT,
    "sportId" INT,
    "teamName" TEXT,
    "shortName" TEXT,
    "franchiseName" TEXT,
    "clubName" TEXT,
    "locationName" TEXT,
    "abbreviation" TEXT,
    "teamCode" TEXT,
    "fileCode" TEXT,
    "teamLink" TEXT,
    "venueName" TEXT,
    "venueLink" TEXT,
    "leagueName" TEXT,
    "leagueLink" TEXT,
    "divisionName" TEXT,
    "divisionLink" TEXT,
    "springLeagueName" TEXT,
    "springLeagueLink" TEXT,
    "springLeagueAbbreviation" TEXT,
    "springVenueLink" TEXT,
    "sportLink" TEXT,
    "firstYearOfPlay" INT,
    "season" INT,
    "allStarStatus" TEXT,
    "isActive" BOOLEAN,
    "_createdAt" timestamp
)