Select
    play_outcome_play_id,
    about_at_bat_index,
    about_game_id,
    matchup_batter_id,
    matchup_pitcher_id,
    matchup_post_on_first_id,
    matchup_post_on_second_id,
    matchup_post_on_third_id,
    about_half_inning,
    about_inning,
    EXTRACT(EPOCH FROM (play_outcome_start_time - play_outcome_end_time)) as play_duration_seconds,
    matchup_splits_batter,
    matchup_splits_pitcher,
    matchup_splits_men_on_base,
    play_outcome_is_strike,
    play_outcome_is_ball,
    play_outcome_is_out,
    play_outcome_is_in_play,
    play_outcome_type_code,
    play_outcome_details_call_code,
    play_outcome_pitch_data_start_speed,
    play_outcome_pitch_data_end_speed,
    play_outcome_hit_data_launch_speed,
    play_outcome_hit_data_launch_angle,
    play_outcome_hit_data_total_distance,
    play_outcome_hit_data_hardness,
    play_outcome_hit_data_trajectory,
    play_outcome_hit_data_location,
    play_outcome_pitch_number,
    play_outcome_start_time,
    play_outcome_end_time
    --,p.*
from baseball_platinum.plays p
where play_outcome_type = 'pitch'